import { client } from '../libs/client';

import Head from 'next/head'

import { Cart, Footer, FooterBanner, HeroBanner, Navbar, Product } from '../components';

import { Box, Container, Grid, GridItem, Heading, Text } from '@chakra-ui/react'

export default function Home({ banners, products }) {
  console.log('products', products)
  return (
    <Container maxW='container.xl'>
      <Head>
        <title>Ecommerce store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {banners && banners.length > 0 && < HeroBanner {...banners[0]} />}

      <Box textAlign="center" py={10} px={6}>
        <Heading as="h2" size="xl" fontWeight='bold' mt={6} mb={2} color="blue.900">
          Best Sellers Products
        </Heading>
        <Text color={'gray.500'}>
          Lorem ipsum dolor sit amet, consetetur sadipscing elitr.
        </Text>
      </Box>
      <Grid templateColumns='repeat(3, 1fr)' justifyContent="space-between" alignItems='center' gap={12}>
        {products && products.length > 0 && products?.map((product, index) =>
          <GridItem key={`product_${product?._id}_${index}`}>
            <Product {...product} />
          </GridItem>
        )}
      </Grid>

      <Footer />


    </Container>
  )
}

export async function getStaticProps() {
  const banners = await client.fetch(`*[_type == "banner"]`);
  const products = await client.fetch(`*[_type == "product"]`);

  return {
    props: {
      banners,
      products
    }
  };
}
